#!/bin/bash
set -euxo pipefail

KANATA_VERSION="v1.11.0"
KANATA_SHA256="d9f634afb4c7f078cc2aacf3998fd65b432d4d83296cc48a89f941525459b4e2"
WAYLE_VERSION="v0.6.0"
# sha256 of wayle-0.6.0-1.fc44.x86_64.rpm from the v0.6.0 SHA256SUMS asset.
WAYLE_RPM_SHA256="7484bf10d56b3de323cb115abe2d0a10dc1b262e4a2e1f12924c2d5a0524c988"

# --- blacktau/hyprland COPR ---
# Fedora 44 retired the in-tree hyprland packages, so a third-party COPR is
# required. blacktau/hyprland is the only F44 COPR with a self-consistent
# stack: aquamarine 0.11 (linked against libdisplay-info.so.3, matching
# Fedora 44) plus hyprland 0.55.4, hyprgraphics 0.5.1, hyprlock 0.9.5, and
# xdg-desktop-portal-hyprland 1.3.12 — all SONAMEs satisfy each other.
# (solopasha's aquamarine still needs .so.2; omadora ships only the deps;
# eli-xciv's hyprland needs libhyprgraphics.so.1 but ships .so.4.)
FEDORA_VERSION="$(rpm -E %fedora)"
curl -fsSL \
  "https://copr.fedorainfracloud.org/coprs/blacktau/hyprland/repo/fedora-${FEDORA_VERSION}/blacktau-hyprland-fedora-${FEDORA_VERSION}.repo" \
  -o /etc/yum.repos.d/_copr_blacktau-hyprland.repo
# COPR repo files ship skip_if_unavailable=True, which makes transient CDN
# 404s during repodata fetch silently disable the repo — followed by an
# unhelpful "No match for argument: hyprland". Force the repo to fail loudly
# so the retry loop below can react.
sed -i 's/^skip_if_unavailable=True$/skip_if_unavailable=False/' \
  /etc/yum.repos.d/_copr_blacktau-hyprland.repo

# COPR metadata hashes rotate while builds are pushed; retry through the race.
for attempt in 1 2 3 4 5; do
  if dnf5 makecache --refresh -y; then
    break
  fi
  echo "dnf5 makecache attempt ${attempt} failed; retrying in 10s..."
  sleep 10
done

# --- Runtime stack ---
# Note: xdg-desktop-portal-gtk, wl-clipboard, tmux, and fzf ship in the
# bluefin-dx base image; dnf5 errors on "already installed", so they are
# intentionally omitted. hypridle/hyprpaper are also omitted because Wayle's
# `shell` subcommand provides idle and wallpaper management.
dnf5 install -y \
  hyprland \
  xdg-desktop-portal-hyprland \
  hyprlock \
  kitty \
  alacritty \
  fuzzel \
  cliphist \
  brightnessctl \
  grim \
  slurp \
  pavucontrol \
  fd-find \
  ripgrep \
  jq

# --- kanata: fetch pinned release, verify sha256, install ---
TMP="$(mktemp -d)"
curl -fsSL -o "$TMP/kanata.zip" \
  "https://github.com/jtroo/kanata/releases/download/${KANATA_VERSION}/linux-binaries-x64.zip"
echo "${KANATA_SHA256}  $TMP/kanata.zip" | sha256sum -c -
( cd "$TMP" && unzip -q kanata.zip )
KANATA_BIN="$(find "$TMP" -maxdepth 3 -type f -name 'kanata*' ! -name '*.zip' -executable -print -quit \
  || find "$TMP" -maxdepth 3 -type f -name 'kanata*' ! -name '*.zip' -print -quit)"
install -m0755 "$KANATA_BIN" /usr/bin/kanata
rm -rf "$TMP"

groupadd --system uinput || true
cat >/etc/udev/rules.d/99-input.rules <<'EOF'
KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
EOF
echo uinput >/etc/modules-load.d/uinput.conf

# --- Wayle: install the upstream prebuilt RPM (avoids the Rust toolchain) ---
# Pinned to fc44 — when the base image moves to fc45 we'll need a matching
# upstream RPM or to fall back to a source build for that window.
WAYLE_TMP="$(mktemp -d)"
WAYLE_RPM="${WAYLE_TMP}/wayle.rpm"
curl -fsSL -o "${WAYLE_RPM}" \
  "https://github.com/wayle-rs/wayle/releases/download/${WAYLE_VERSION}/wayle-${WAYLE_VERSION#v}-1.fc44.x86_64.rpm"
echo "${WAYLE_RPM_SHA256}  ${WAYLE_RPM}" | sha256sum -c -
dnf5 install -y "${WAYLE_RPM}"
rm -rf "${WAYLE_TMP}"

# --- Ship default skel configs ---
if [ -d /ctx/skel ]; then
  cp -a /ctx/skel/. /etc/skel/
fi

# --- Hyprland config: seed default for already-existing users ---
# /etc/skel only seeds NEW accounts. Existing users rebasing into this
# image never get the default hyprland.conf, so Hyprland autogenerates a
# bare hyprland.lua and emits a "you're on the autogenerated config"
# warning. Ship a systemd --user oneshot that copies the default into
# $HOME on login when it's missing. cp -n + ConditionPathExists guard
# against ever clobbering a user edit.
cat >/usr/lib/systemd/user/hyprland-config-seed.service <<'EOF'
[Unit]
Description=Seed default Hyprland config from /etc/skel
ConditionPathExists=!%h/.config/hypr/hyprland.conf
ConditionPathExists=/etc/skel/.config/hypr/hyprland.conf

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'mkdir -p "$HOME/.config/hypr" && cp -n /etc/skel/.config/hypr/hyprland.conf "$HOME/.config/hypr/hyprland.conf"'

[Install]
WantedBy=default.target
EOF
mkdir -p /usr/lib/systemd/user/default.target.wants
ln -sf ../hyprland-config-seed.service \
  /usr/lib/systemd/user/default.target.wants/hyprland-config-seed.service
